# Generated by Django 3.2 on 2023-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='blog_comments', to='blog.CommentModel'),
        ),
    ]
