# Generated by Django 3.2 on 2023-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_imageblogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog'),
        ),
        migrations.DeleteModel(
            name='ImageBlogPost',
        ),
    ]
